<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pravins-MacBook-Pro.local" failures="1" tests="1" name="runner.TestReRunner" time="8.644" errors="0" timestamp="2024-05-28T21:13:27 IST" skipped="0">
  <testcase classname="runner.TestReRunner" name="runScenario" time="8.644">
    <failure message="expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at stepDefination.LoginStep.user_will_verify_homepage(LoginStep.java:47)
at âœ½.user will verify homepage(file:///Users/pravintambare/Documents/workspace-spring-tool-suite-4-4.13.1.RELEASE/Framework2324/src/test/resources/feature/Login.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestReRunner -->
